 module.exports = [
  './gulp/tasks/pug',
  './gulp/tasks/sass',
  './gulp/tasks/javaScript',
  './gulp/tasks/grid',
  './gulp/tasks/pngSprite',
  './gulp/tasks/svgSprite',
  './gulp/tasks/img',
  './gulp/tasks/fontmin',
  './gulp/tasks/woff2',
  './gulp/tasks/fonts',
  './gulp/tasks/clean',
  './gulp/tasks/serve',
  './gulp/tasks/watch',
 ];
