import $ from 'jquery';
import 'fullpage.js/dist/jquery.fullpage.min';
import 'fullpage.js/dist/jquery.fullpage.extensions.min';
import 'tooltipster/dist/js/tooltipster.bundle.min';
import 'tooltipster-follower/dist/js/tooltipster-follower.min';
import './fullPage-settings';
import './burger';
import './modal';
import './map';
import './tooltip';
